---
timeout: 1800s
steps:
  # Load secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud secrets versions access latest --secret="$PROJECT_ID"-github-token > gh_token.txt
        gcloud secrets versions access latest --secret="$PROJECT_ID"-npm-token > npm_token.txt
        # NPM_TOKEN=$(gcloud secrets versions access latest --secret="$PROJECT_ID"-npm-token)
        # echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" > .npmrc
  # Install deps.
  - name: 'node:12'
    entrypoint: 'npm'
    args:
      - 'install'
  # Run build
  - name: 'node:12'
    entrypoint: 'npm'
    args:
      - 'run'
      - 'build'
  # Publish package.
  - name: 'node:12'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export GH_TOKEN=$(cat "gh_token.txt")
        export NPM_TOKEN=$(cat "npm_token.txt")
        npm run semantic-release
